### ISSUE TITLE
Customise website contact form

### ISSUE THREAD

**Issue by KylieStedmanGomes** [Praxorium/praxorium.github.io#3]
There are 2 files related to the contact form for the website: contact.html and contact_process.php.

The files are currently located in the praxorium_site folder in Dropbox: https://www.dropbox.com/sh/aae0nxjtm0lv71p/AACkLLLvvCmdA6qRninVQ-_la?dl=0

I've updated the contact.html file to display only the fields I want on the contact form.

Would you please apply your magic to make the form work? 

If there's any high elf magic you can perform to guard against spam, that would be even better.

**Comment by manuelgomes** [comment]
Magic applied
